# Generated by Django 6.0.1 on 2026-01-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный возраст')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный возраст')),
            ],
            options={
                'verbose_name': 'Возрастная категория',
                'verbose_name_plural': 'Возрастные категории',
                'ordering': ['min_age', 'max_age'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название этапа')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код этапа')),
            ],
            options={
                'verbose_name': 'Этап участия',
                'verbose_name_plural': 'Этапы участия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=225, verbose_name='Имя')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статуса')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код статуса')),
            ],
            options={
                'verbose_name': 'Статус проекта',
                'verbose_name_plural': 'Статусы проекта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название конференции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн-формат')),
                ('organizers', models.ManyToManyField(blank=True, related_name='organized_conferences', to='users.user', verbose_name='Организаторы')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип представления')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='conf.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Тип представления',
                'verbose_name_plural': 'Типы представления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('files', models.FileField(blank=True, null=True, upload_to='projects/files/', verbose_name='Файлы проекта')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_projects', to='users.user', verbose_name='Руководитель проекта')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to='users.user', verbose_name='Участники')),
                ('presentation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='conf.presentationtype', verbose_name='Тип представления')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='conf.participationstage', verbose_name='Этап участия')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_projects', to='users.user', verbose_name='Научный руководитель')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='conf.projectstatus', verbose_name='Статус проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='users.user', verbose_name='Автор комментария')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='conf.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название секции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='conf.agecategory', verbose_name='Возрастная категория')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='conf.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='conf.section', verbose_name='Секция'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('title', 'section', 'leader'), name='unique_project_title_section_leader'),
        ),
    ]
