# Generated by Django 6.0.1 on 2026-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_conference_prizes_count_conference_results_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Очно'), ('hybrid', 'Смешанный')], default='offline', max_length=20, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн-формат (устаревшее)'),
        ),
    ]
