# Generated by Django 6.0.1 on 2026-01-31 11:45

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conf", "0003_conference_format_alter_conference_is_online"),
        ("users", "0002_alter_user_managers_user_date_joined_user_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "stage",
                    models.CharField(
                        choices=[("online", "Заочный этап"), ("offline", "Очный этап")],
                        default="online",
                        max_length=10,
                        verbose_name="Этап проверки",
                    ),
                ),
                ("max_projects", models.PositiveIntegerField(default=0, verbose_name="Лимит проектов")),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_assignments",
                        to="conf.conference",
                        verbose_name="Конференция",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Эксперт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение эксперту",
                "verbose_name_plural": "Назначения экспертам",
            },
        ),
        migrations.CreateModel(
            name="ExpertAssignmentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="conf.expertassignment",
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_assignments",
                        to="conf.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект эксперта",
                "verbose_name_plural": "Проекты экспертов",
            },
        ),
        migrations.AddConstraint(
            model_name="expertassignment",
            constraint=models.UniqueConstraint(
                fields=["conference", "expert", "stage"],
                name="unique_conference_expert_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="expertassignmentitem",
            constraint=models.UniqueConstraint(
                fields=["assignment", "project"],
                name="unique_assignment_project",
            ),
        ),
    ]
