# Generated by Django 6.0.1 on 2026-02-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conf", "0004_expert_assignment_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceStatusFlowItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_flow_items",
                        to="conf.conference",
                        verbose_name="Конференция",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_status_items",
                        to="conf.projectstatus",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Воронка статусов конференции",
                "verbose_name_plural": "Воронки статусов конференций",
                "ordering": ["order", "id"],
                "unique_together": {("conference", "status")},
            },
        ),
        migrations.CreateModel(
            name="ConferenceStageAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_items",
                        to="conf.conference",
                        verbose_name="Конференция",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_stage_items",
                        to="conf.participationstage",
                        verbose_name="Этап",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап участия конференции",
                "verbose_name_plural": "Этапы участия конференций",
                "ordering": ["stage__name", "id"],
                "unique_together": {("conference", "stage")},
            },
        ),
    ]
