# Generated by Django 6.0.1 on 2026-02-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conf", "0005_conference_status_flow_and_stages"),
        ("users", "0002_alter_user_managers_user_date_joined_user_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceExpert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_experts",
                        to="conf.conference",
                        verbose_name="Конференция",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_expert_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Эксперт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эксперт конференции",
                "verbose_name_plural": "Эксперты конференций",
                "unique_together": {("conference", "expert")},
            },
        ),
        migrations.AddField(
            model_name="conferenceexpert",
            name="sections",
            field=models.ManyToManyField(
                blank=True,
                related_name="conference_experts",
                to="conf.section",
                verbose_name="Секции эксперта",
            ),
        ),
    ]
