# Generated by Django 6.0.1 on 2026-03-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0007_catalog_per_conference'),
        ('users', '0005_studentteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.studentteam', verbose_name='Команда'),
        ),
    ]
