# Generated by Django 6.0.1 on 2026-02-11 07:32

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_student_roles_and_user_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.EmailUserManager()),
            ],
        ),
    ]
