# Generated by Django 6.0.1 on 2026-03-11 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorStudentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_tutor_links', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_student_links', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'Доступ наставника к участнику',
                'verbose_name_plural': 'Доступы наставников к участникам',
                'constraints': [models.UniqueConstraint(fields=('tutor', 'student'), name='unique_tutor_student_access')],
            },
        ),
    ]
