# Generated by Django 6.0.1 on 2026-03-14 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('members', models.ManyToManyField(blank=True, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_student_teams', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'Команда учеников',
                'verbose_name_plural': 'Команды учеников',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tutor', 'name'), name='unique_student_team_name_per_tutor')],
            },
        ),
    ]
