# Generated by Django 6.0.1 on 2026-03-14 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tutorstudentaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPeerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_of_links', to=settings.AUTH_USER_MODEL, verbose_name='Связанный ученик')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_links', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Связь между учениками',
                'verbose_name_plural': 'Связи между учениками',
                'constraints': [models.UniqueConstraint(fields=('student', 'peer'), name='unique_student_peer_link')],
            },
        ),
    ]
