/**
 * Коды стран для телефона (E.164). Россия первой по умолчанию.
 * Формат: { code: код без "+", name: название, iso2: ISO 3166-1 alpha-2 для флага }
 */
export type PhoneCountry = { code: string; name: string; iso2: string };

export const PHONE_COUNTRY_CODES: PhoneCountry[] = [
  { code: "7", name: "Россия", iso2: "RU" },
  { code: "7", name: "Казахстан", iso2: "KZ" },
  { code: "375", name: "Беларусь", iso2: "BY" },
  { code: "380", name: "Украина", iso2: "UA" },
  { code: "996", name: "Киргизия", iso2: "KG" },
  { code: "998", name: "Узбекистан", iso2: "UZ" },
  { code: "992", name: "Таджикистан", iso2: "TJ" },
  { code: "993", name: "Туркменистан", iso2: "TM" },
  { code: "994", name: "Азербайджан", iso2: "AZ" },
  { code: "995", name: "Грузия", iso2: "GE" },
  { code: "374", name: "Армения", iso2: "AM" },
  { code: "373", name: "Молдова", iso2: "MD" },
  { code: "1", name: "США", iso2: "US" },
  { code: "1", name: "Канада", iso2: "CA" },
  { code: "44", name: "Великобритания", iso2: "GB" },
  { code: "49", name: "Германия", iso2: "DE" },
  { code: "33", name: "Франция", iso2: "FR" },
  { code: "39", name: "Италия", iso2: "IT" },
  { code: "34", name: "Испания", iso2: "ES" },
  { code: "31", name: "Нидерланды", iso2: "NL" },
  { code: "32", name: "Бельгия", iso2: "BE" },
  { code: "41", name: "Швейцария", iso2: "CH" },
  { code: "43", name: "Австрия", iso2: "AT" },
  { code: "48", name: "Польша", iso2: "PL" },
  { code: "420", name: "Чехия", iso2: "CZ" },
  { code: "421", name: "Словакия", iso2: "SK" },
  { code: "36", name: "Венгрия", iso2: "HU" },
  { code: "40", name: "Румыния", iso2: "RO" },
  { code: "359", name: "Болгария", iso2: "BG" },
  { code: "30", name: "Греция", iso2: "GR" },
  { code: "351", name: "Португалия", iso2: "PT" },
  { code: "353", name: "Ирландия", iso2: "IE" },
  { code: "46", name: "Швеция", iso2: "SE" },
  { code: "47", name: "Норвегия", iso2: "NO" },
  { code: "45", name: "Дания", iso2: "DK" },
  { code: "358", name: "Финляндия", iso2: "FI" },
  { code: "354", name: "Исландия", iso2: "IS" },
  { code: "352", name: "Люксембург", iso2: "LU" },
  { code: "370", name: "Литва", iso2: "LT" },
  { code: "371", name: "Латвия", iso2: "LV" },
  { code: "372", name: "Эстония", iso2: "EE" },
  { code: "385", name: "Хорватия", iso2: "HR" },
  { code: "386", name: "Словения", iso2: "SI" },
  { code: "387", name: "Босния и Герцеговина", iso2: "BA" },
  { code: "381", name: "Сербия", iso2: "RS" },
  { code: "382", name: "Черногория", iso2: "ME" },
  { code: "389", name: "Северная Македония", iso2: "MK" },
  { code: "355", name: "Албания", iso2: "AL" },
  { code: "383", name: "Косово", iso2: "XK" },
  { code: "90", name: "Турция", iso2: "TR" },
  { code: "86", name: "Китай", iso2: "CN" },
  { code: "81", name: "Япония", iso2: "JP" },
  { code: "82", name: "Южная Корея", iso2: "KR" },
  { code: "852", name: "Гонконг", iso2: "HK" },
  { code: "853", name: "Макао", iso2: "MO" },
  { code: "886", name: "Тайвань", iso2: "TW" },
  { code: "91", name: "Индия", iso2: "IN" },
  { code: "92", name: "Пакистан", iso2: "PK" },
  { code: "880", name: "Бангладеш", iso2: "BD" },
  { code: "94", name: "Шри-Ланка", iso2: "LK" },
  { code: "960", name: "Мальдивы", iso2: "MV" },
  { code: "977", name: "Непал", iso2: "NP" },
  { code: "975", name: "Бутан", iso2: "BT" },
  { code: "95", name: "Мьянма", iso2: "MM" },
  { code: "66", name: "Таиланд", iso2: "TH" },
  { code: "84", name: "Вьетнам", iso2: "VN" },
  { code: "65", name: "Сингапур", iso2: "SG" },
  { code: "60", name: "Малайзия", iso2: "MY" },
  { code: "62", name: "Индонезия", iso2: "ID" },
  { code: "63", name: "Филиппины", iso2: "PH" },
  { code: "673", name: "Бруней", iso2: "BN" },
  { code: "855", name: "Камбоджа", iso2: "KH" },
  { code: "856", name: "Лаос", iso2: "LA" },
  { code: "670", name: "Восточный Тимор", iso2: "TL" },
  { code: "61", name: "Австралия", iso2: "AU" },
  { code: "64", name: "Новая Зеландия", iso2: "NZ" },
  { code: "679", name: "Фиджи", iso2: "FJ" },
  { code: "685", name: "Самоа", iso2: "WS" },
  { code: "686", name: "Кирибати", iso2: "KI" },
  { code: "691", name: "Микронезия", iso2: "FM" },
  { code: "692", name: "Маршалловы Острова", iso2: "MH" },
  { code: "976", name: "Монголия", iso2: "MN" },
  { code: "850", name: "КНДР", iso2: "KP" },
  { code: "98", name: "Иран", iso2: "IR" },
  { code: "964", name: "Ирак", iso2: "IQ" },
  { code: "962", name: "Иордания", iso2: "JO" },
  { code: "961", name: "Ливан", iso2: "LB" },
  { code: "963", name: "Сирия", iso2: "SY" },
  { code: "966", name: "Саудовская Аравия", iso2: "SA" },
  { code: "971", name: "ОАЭ", iso2: "AE" },
  { code: "973", name: "Бахрейн", iso2: "BH" },
  { code: "974", name: "Катар", iso2: "QA" },
  { code: "965", name: "Кувейт", iso2: "KW" },
  { code: "968", name: "Оман", iso2: "OM" },
  { code: "967", name: "Йемен", iso2: "YE" },
  { code: "972", name: "Израиль", iso2: "IL" },
  { code: "970", name: "Палестина", iso2: "PS" },
  { code: "20", name: "Египет", iso2: "EG" },
  { code: "213", name: "Алжир", iso2: "DZ" },
  { code: "212", name: "Марокко", iso2: "MA" },
  { code: "216", name: "Тунис", iso2: "TN" },
  { code: "218", name: "Ливия", iso2: "LY" },
  { code: "249", name: "Судан", iso2: "SD" },
  { code: "27", name: "ЮАР", iso2: "ZA" },
  { code: "234", name: "Нигерия", iso2: "NG" },
  { code: "254", name: "Кения", iso2: "KE" },
  { code: "255", name: "Танзания", iso2: "TZ" },
  { code: "256", name: "Уганда", iso2: "UG" },
  { code: "251", name: "Эфиопия", iso2: "ET" },
  { code: "233", name: "Гана", iso2: "GH" },
  { code: "225", name: "Кот-д'Ивуар", iso2: "CI" },
  { code: "223", name: "Мали", iso2: "ML" },
  { code: "221", name: "Сенегал", iso2: "SN" },
  { code: "224", name: "Гвинея", iso2: "GN" },
  { code: "226", name: "Буркина-Фасо", iso2: "BF" },
  { code: "227", name: "Нигер", iso2: "NE" },
  { code: "228", name: "Того", iso2: "TG" },
  { code: "229", name: "Бенин", iso2: "BJ" },
  { code: "230", name: "Маврикий", iso2: "MU" },
  { code: "261", name: "Мадагаскар", iso2: "MG" },
  { code: "237", name: "Камерун", iso2: "CM" },
  { code: "243", name: "ДР Конго", iso2: "CD" },
  { code: "242", name: "Конго", iso2: "CG" },
  { code: "257", name: "Бурунди", iso2: "BI" },
  { code: "250", name: "Руанда", iso2: "RW" },
  { code: "260", name: "Замбия", iso2: "ZM" },
  { code: "263", name: "Зимбабве", iso2: "ZW" },
  { code: "267", name: "Ботсвана", iso2: "BW" },
  { code: "264", name: "Намибия", iso2: "NA" },
  { code: "258", name: "Мозамбик", iso2: "MZ" },
  { code: "265", name: "Малави", iso2: "MW" },
  { code: "266", name: "Лесото", iso2: "LS" },
  { code: "268", name: "Эсватини", iso2: "SZ" },
  { code: "269", name: "Коморы", iso2: "KM" },
  { code: "248", name: "Сейшелы", iso2: "SC" },
  { code: "55", name: "Бразилия", iso2: "BR" },
  { code: "54", name: "Аргентина", iso2: "AR" },
  { code: "56", name: "Чили", iso2: "CL" },
  { code: "57", name: "Колумбия", iso2: "CO" },
  { code: "58", name: "Венесуэла", iso2: "VE" },
  { code: "51", name: "Перу", iso2: "PE" },
  { code: "593", name: "Эквадор", iso2: "EC" },
  { code: "595", name: "Парагвай", iso2: "PY" },
  { code: "598", name: "Уругвай", iso2: "UY" },
  { code: "591", name: "Боливия", iso2: "BO" },
  { code: "592", name: "Гайана", iso2: "GY" },
  { code: "594", name: "Французская Гвиана", iso2: "GF" },
  { code: "597", name: "Суринам", iso2: "SR" },
  { code: "509", name: "Гаити", iso2: "HT" },
  { code: "53", name: "Куба", iso2: "CU" },
  { code: "1", name: "Ямайка", iso2: "JM" },
  { code: "1", name: "Доминиканская Республика", iso2: "DO" },
  { code: "1", name: "Пуэрто-Рико", iso2: "PR" },
  { code: "502", name: "Гватемала", iso2: "GT" },
  { code: "503", name: "Сальвадор", iso2: "SV" },
  { code: "504", name: "Гондурас", iso2: "HN" },
  { code: "505", name: "Никарагуа", iso2: "NI" },
  { code: "506", name: "Коста-Рика", iso2: "CR" },
  { code: "507", name: "Панама", iso2: "PA" },
  { code: "52", name: "Мексика", iso2: "MX" },
];

/** Значение по умолчанию (Россия): code|iso2 для уникальности в Select */
export const DEFAULT_PHONE_COUNTRY_VALUE = "7|RU";

/** Флаг страны по ISO 3166-1 alpha-2 (две буквы A-Z) */
export function getCountryFlag(iso2: string): string {
  if (!iso2 || iso2.length !== 2) return "";
  const a = iso2.toUpperCase().charCodeAt(0) - 0x41;
  const b = iso2.toUpperCase().charCodeAt(1) - 0x41;
  if (a < 0 || a > 25 || b < 0 || b > 25) return "";
  return String.fromCodePoint(0x1f1e6 + a, 0x1f1e6 + b);
}

/** Из значения Select (code|iso2) получить код набора */
export function getDialCodeFromValue(value: string): string {
  const code = value.split("|")[0];
  return code || "7";
}
